--- # loop example
- hosts: localhost
  become: true
  tasks:
    - name: install software
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - elinks
        - nmap-ncat
        - bind-utils
